const Log = require("./logger");

const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiIyMzQ4MWExMmszQGdlY2d1ZGxhdmFsbGVydW1pYy5pbiIsImV4cCI6MTc3ODMxMTU3MiwiaWF0IjoxNzc4MzEwNjcyLCJpc3MiOiJBZmZvcmQgTWVkaWNhbCBUZWNobm9sb2dpZXMgUHJpdmF0ZSBMaW1pdGVkIiwianRpIjoiMTQ5NWQ3NjItNTlhNy00MDBjLTg0YTktMTExMzYwN2Y0MGEyIiwibG9jYWxlIjoiZW4tSU4iLCJuYW1lIjoic2FuaXlhIHRhcnVubmFtIiwic3ViIjoiNmU3YzYyNTgtMWQ3Ny00MGJlLTlhMzQtZjIxMGJhMjg1ZWZhIn0sImVtYWlsIjoiMjM0ODFhMTJrM0BnZWNndWRsYXZhbGxlcnVtaWMuaW4iLCJuYW1lIjoic2FuaXlhIHRhcnVubmFtIiwicm9sbE5vIjoiMjM0ODFhMTJrMyIsImFjY2Vzc0NvZGUiOiJlSmRDdUMiLCJjbGllbnRJRCI6IjZlN2M2MjU4LTFkNzctNDBiZS05YTM0LWYyMTBiYTI4NWVmYSIsImNsaWVudFNlY3JldCI6ImJQc0hRWm1CekFOS3daVFAifQ.JOFjCkLCeTtEHUvPkyphQwdzk8N7_PPT90IKArbjrds";
Log(
  "backend",
  "error",
  "handler",
  "received string, expected bool",
  token
);